### ISSUE TITLE
 Метод сброса контроллера к заводским настройкам

### ISSUE THREAD

**Issue by fc-arny** [Z-Wave-Me/O7#15]

**Comment by PoltoS** [comment]
Зажать кнопку в углу (WPS) и удерживая её перезагрузить контроллер кнопкой Reset (нажать иголкой). Удерживать кнопку в углу (WPS) пока контроллер не начёт быстро мигать светодиодом. Отпустить кнопку (WPS)

Подождать, пока контроллер не начнёт медленно мигать.

Готово
